title: Chizoba Obasi blog
description: Musings of a deep learning enthusiast. Bookmark this website to keep an eye on my articles & project updates!
github_username: chizkidd
kaggle_username: chizkidd
url: "https://chizkidd.github.io/"

theme: minima
# theme: jekyll-theme-minimal

# author:
#   name: Chizoba Obasi

# # Minima theme options
# jekyll-theme-minimal:
#   # accent_color: "#ff6600"  # Customize the accent color
#   social_links:
#     rss: true
#     github: chizkidd

# Navigation links
header_pages:
  - about.md
  
# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks structure
permalink: /:categories/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Chizoba Obasi"
