# Site settings
title: Chizoba Obasi blog
email:
description: "Musings of a Deep Learning Enthusiast." # Bookmark this website to keep an eye on my articles & project updates!
baseurl: ""
url: "https://chizkidd.github.io/"

# Social links
twitter_username: chizkidd
github_username: chizkidd
kaggle_username: chizkidd

# Build settings
markdown: kramdown
permalink: pretty
# theme: minima
# theme: jekyll-theme-minimal

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge


# # Plugins
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag

# # RSS Feed settings
# feed:
#   path: feed.xml



# # Minima theme specific settings
# minima:
#   social_links:
#     - platform: rss
#       user_url: /feed.xml
#     - platform: github
#       user_url: https://github.com/chizkidd
#     - platform: kaggle
#       user_url: https://www.kaggle.com/chizkidd
#     - platform: twitter
#       user_url: https://twitter.com/chizkidd

# # Navigation
# header_pages:
#   - about.md

# # Defaults
# defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"
#       author: "Chizoba Obasi"

# # Excerpt settings
# excerpt_length: 50
