title: Chizoba Obasi blog
email:
description: "Musings of a deep learning enthusiast." # Bookmark this website to keep an eye on my articles & project updates!
github_username: chizkidd
# twitter_username: chizkidd
# kaggle_username: chizkidd
url: "https://chizkidd.github.io/"

theme: minima
# theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge


# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# # RSS feed settings
# feed:
#   path: feed.xml

# # Minima theme specific settings
# minima:
#   social_links:
#     - platform: rss
#       user_url: /feed.xml
#     - platform: github
#       user_url: https://github.com/chizkidd
#     - platform: kaggle
#       user_url: https://www.kaggle.com/chizkidd
#     - platform: twitter
#       user_url: https://twitter.com/chizkidd

# social-network-links:
#   rss: true
#   kaggle: chizkidd
#   github: chizkidd
#   twitter: chizkidd
  
# author:
#   name: Chizoba Obasi

# # Minima theme options
# jekyll-theme-minimal:
#   # accent_color: "#ff6600"  # Customize the accent color
#   social_links:
#     rss: true
#     github: chizkidd

# # Navigation links
# header_pages:
#   - about.md
  
# # Plugins
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag

# # Markdown settings
# markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge

# # Permalinks structure
# permalink: /:categories/:year/:month/:day/:title/

# # Defaults
# defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"
#       author: "Chizoba Obasi"
